export const defaultScenarioData = {
  title: 'Operation Signal Break',
  fictionalLocation: 'NavDrishti Corridor',
  description:
    'Fictional emergency coordination and relief supply convoy escort training exercise under multi-point degraded communication and conflicting intelligence.',
  objective:
    'Deliver one critical medical and shelter supply package from Base Orion to Zone C before exercise conclusion, navigating information delays, dropped messages, and route disruptions.',
  difficulty: 'MEDIUM',
  durationSeconds: 600,
  roles: [
    'COMMANDER',
    'TEAM_ALPHA',
    'TEAM_BRAVO',
    'AIR_OBSERVATION',
    'LOGISTICS',
    'INSTRUCTOR',
    'OBSERVER',
  ],
  zones: [
    { id: 'zone-base', name: 'Base Orion', lat: 34.12, lng: 74.8, type: 'BASE', description: 'Main expedition and logistics assembly base.' },
    { id: 'zone-c', name: 'Zone C (Civilian Relief Post)', lat: 34.2, lng: 74.95, type: 'OBJECTIVE', description: 'Target delivery post awaiting critical medical supplies.' },
    { id: 'zone-obs-ridge', name: 'Observation Ridge', lat: 34.17, lng: 74.84, type: 'CHECKPOINT', description: 'High-elevation lookout post for Team Alpha.' },
    { id: 'zone-relay', name: 'Relay Point Sigma', lat: 34.145, lng: 74.89, type: 'RELAY', description: 'Intermediate communications booster tower.' },
    { id: 'zone-contingency', name: 'Contingency Valley', lat: 34.11, lng: 74.92, type: 'CHECKPOINT', description: 'Southern staging area guarded by Team Bravo.' },
  ],
  routes: [
    {
      id: 'route-north',
      name: 'North Ridge Pass',
      waypoints: [
        [34.12, 74.8],
        [34.15, 74.82],
        [34.17, 74.84],
        [34.19, 74.89],
        [34.2, 74.95],
      ],
      groundTruthStatus: 'BLOCKED',
      perceivedStatus: {
        COMMANDER: 'CLEAR',
        TEAM_ALPHA: 'BLOCKED',
        TEAM_BRAVO: 'CLEAR',
        AIR_OBSERVATION: 'CLEAR',
        LOGISTICS: 'CLEAR',
      },
      travelTimeSeconds: 240,
      description: 'Shortest mountain pass, prone to rockfall and landslide blockage.',
    },
    {
      id: 'route-central',
      name: 'Central Corridor Highway',
      waypoints: [
        [34.12, 74.8],
        [34.135, 74.85],
        [34.145, 74.89],
        [34.175, 74.92],
        [34.2, 74.95],
      ],
      groundTruthStatus: 'DEGRADED',
      perceivedStatus: {
        COMMANDER: 'CLEAR',
        TEAM_ALPHA: 'CLEAR',
        TEAM_BRAVO: 'CLEAR',
        AIR_OBSERVATION: 'CLEAR',
        LOGISTICS: 'CLEAR',
      },
      travelTimeSeconds: 320,
      description: 'Main highway corridor subject to flash weather slowdowns.',
    },
    {
      id: 'route-south',
      name: 'South Valley Bypass',
      waypoints: [
        [34.12, 74.8],
        [34.11, 74.86],
        [34.11, 74.92],
        [34.16, 74.94],
        [34.2, 74.95],
      ],
      groundTruthStatus: 'CLEAR',
      perceivedStatus: {
        COMMANDER: 'CLEAR',
        TEAM_ALPHA: 'CLEAR',
        TEAM_BRAVO: 'CLEAR',
        AIR_OBSERVATION: 'CLEAR',
        LOGISTICS: 'CLEAR',
      },
      travelTimeSeconds: 380,
      description: 'Longer but secure and open valley route.',
    },
  ],
  resources: {
    supplyPackages: 1,
    vehicles: 1,
    aerialSensors: 1,
  },
  scheduledEvents: [
    {
      id: 'evt-01',
      triggerAtSeconds: 60,
      type: 'REPORT_CREATED',
      targetRole: 'TEAM_ALPHA',
      description: 'Team Alpha scout spots rockslide rubble across North Route.',
      payload: {
        senderRole: 'TEAM_ALPHA',
        recipientRole: 'COMMANDER',
        channel: 'PRIMARY',
        content: 'North Route likely blocked due to debris and rockfall at km 14.',
        relatedSubject: 'ROUTE_NORTH',
        confidence: 'HIGH',
      },
    },
    {
      id: 'evt-02',
      triggerAtSeconds: 90,
      type: 'CONFLICTING_REPORT_INJECTED',
      targetRole: 'AIR_OBSERVATION',
      description: 'Air unit sends report based on stale aerial feed imagery.',
      payload: {
        senderRole: 'AIR_OBSERVATION',
        recipientRole: 'COMMANDER',
        channel: 'PRIMARY',
        content: 'North Route appears clear from older overhead pass. No obstructions visible.',
        relatedSubject: 'ROUTE_NORTH',
        confidence: 'MEDIUM',
        isStale: true,
        freshnessSecondsAgo: 85,
      },
    },
    {
      id: 'evt-03',
      triggerAtSeconds: 150,
      type: 'CHANNEL_DEGRADED',
      targetRole: 'TEAM_ALPHA',
      description: 'Primary RF relay failure causes 45-second latency on Team Alpha transmissions.',
      payload: {
        channel: 'PRIMARY',
        effect: 'DELAY',
        delaySeconds: 45,
        targetRole: 'TEAM_ALPHA',
      },
    },
    {
      id: 'evt-04',
      triggerAtSeconds: 195,
      type: 'REPORT_CREATED',
      targetRole: 'TEAM_ALPHA',
      description: 'Team Alpha sends confirmed blockage report (delayed by 45s in transmission).',
      payload: {
        senderRole: 'TEAM_ALPHA',
        recipientRole: 'COMMANDER',
        channel: 'PRIMARY',
        content: 'URGENT: Landslide confirmed at North Ridge pass. Absolutely impassable for heavy convoy vehicle.',
        relatedSubject: 'ROUTE_NORTH',
        confidence: 'HIGH',
        delayedBySeconds: 45,
      },
    },
    {
      id: 'evt-05',
      triggerAtSeconds: 240,
      type: 'REPORT_CREATED',
      targetRole: 'LOGISTICS',
      description: 'Logistics requests Commander routing clearance.',
      payload: {
        senderRole: 'LOGISTICS',
        recipientRole: 'COMMANDER',
        channel: 'PRIMARY',
        content: 'Convoy ready at Base Orion. Awaiting confirmed route order to dispatch relief vehicle.',
        relatedSubject: 'CONVOY_DEPARTURE',
        confidence: 'HIGH',
      },
    },
    {
      id: 'evt-06',
      triggerAtSeconds: 270,
      type: 'MESSAGE_DROPPED',
      targetRole: 'TEAM_BRAVO',
      description: 'Radio packet loss causes Team Bravo status update to drop silently.',
      payload: {
        senderRole: 'TEAM_BRAVO',
        recipientRole: 'COMMANDER',
        channel: 'PRIMARY',
        content: 'Team Bravo in position at South Valley. Route South is all clear and ready for transit.',
        dropped: true,
      },
    },
    {
      id: 'evt-07',
      triggerAtSeconds: 300,
      type: 'ROUTE_STATUS_CHANGED',
      description: 'Flash rainstorm causes mud conditions on Central Route.',
      payload: {
        routeId: 'route-central',
        newStatus: 'DEGRADED',
        reason: 'Heavy cloudburst flooding over Central Highway.',
      },
    },
    {
      id: 'evt-08',
      triggerAtSeconds: 360,
      type: 'DECISION_CREATED',
      targetRole: 'COMMANDER',
      description: 'Commander required decision milestone for convoy routing.',
      payload: {
        actionPrompt: 'Select route and issue movement order with recorded rationale.',
      },
    },
    {
      id: 'evt-09',
      triggerAtSeconds: 450,
      type: 'BACKUP_CHANNEL_ENABLED',
      description: 'Backup satellite/HF radio link activated.',
      payload: {
        channel: 'BACKUP',
        status: 'AVAILABLE',
      },
    },
    {
      id: 'evt-10',
      triggerAtSeconds: 540,
      type: 'RESOURCE_STATUS_CHANGED',
      description: 'Logistics vehicle en route through safe corridor.',
      payload: {
        vehicleStatus: 'MOVING',
        destination: 'Zone C',
      },
    },
    {
      id: 'evt-11',
      triggerAtSeconds: 600,
      type: 'SESSION_ENDED',
      description: 'Simulation scenario concludes.',
      payload: {
        sessionStatus: 'COMPLETED',
      },
    },
  ],
  scoreWeights: {
    disruptionDetection: 15,
    backupRecovery: 15,
    criticalDeliveryAck: 15,
    freshnessVerification: 15,
    conflictResolution: 10,
    decisionTimeliness: 10,
    teamCoordination: 10,
    adaptability: 5,
    resourceEfficiency: 5,
  },
};
